name: tests
on: [pull_request]
jobs:
  build-test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        btype: [Release, Debug]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
      - run: cmake -DCMAKE_PREFIX_PATH="`pip show torch | grep -oP '(?<=Location:\ ).*'`/torch/share/cmake" -DCMAKE_BUILD_TYPE=${{ matrix.btype }} .
      - run: make -j 2
      - run: make test
